version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - DEBUG=True
      - TESTING=True
    command: make test 